# Generated by Django 3.2.8 on 2021-10-10 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('idtipoDocumento', models.IntegerField()),
                ('documento', models.IntegerField()),
                ('fecha_nacimiento', models.DateField()),
            ],
        ),
    ]
